class_name PassiveState
extends RefCounted

## Runtime state for mutually exclusive passive modules.
## The actor keeps its normal CombatState; Baroud owns only its temporary
## last-chance gauge and Omnivamp returns a heal amount from effective damage.

const BAROUD_MAX_HEALTH := 1000.0
const BAROUD_DURATION := 2.5
const BAROUD_DRAIN_PER_SECOND := 400.0
const OMNIVAMP_RATE := 0.15
const DATA := preload("res://scripts/combat_data.gd")
const IDS := ["baroud", "omnivamp", "auxiliary_reactor", "tracker", "alternator", "inertia"]

var tuning: Dictionary = {}
var reactor_remaining := 0.0
var tracker_count := 0
var tracker_remaining := 0.0
var alternator_remaining := 0.0
var inertia_remaining := 0.0
var pulse_remaining := 0.0
var _epoch := 0
var _serial := 0
var _tracker_target := 0
var _revealed: Dictionary = {}
var _reveal_targets: Dictionary = {}
var replica_reveal_remaining := 0.0
var _modules: Dictionary = {}


func clear_triggers() -> void:
	_epoch += 1
	reactor_remaining = 0.0
	tracker_count = 0
	tracker_remaining = 0.0
	alternator_remaining = 0.0
	inertia_remaining = 0.0
	pulse_remaining = 0.0
	_tracker_target = 0
	_revealed.clear()
	_reveal_targets.clear()
	replica_reveal_remaining = 0.0
	_modules.clear()


func tick_triggers(delta: float) -> void:
	reactor_remaining = maxf(0.0, reactor_remaining - delta)
	tracker_remaining = maxf(-0.000001, tracker_remaining - delta)
	alternator_remaining = maxf(0.0, alternator_remaining - delta)
	inertia_remaining = maxf(0.0, inertia_remaining - delta)
	pulse_remaining = maxf(0.0, pulse_remaining - delta)
	replica_reveal_remaining = maxf(0.0, replica_reveal_remaining - delta)
	if tracker_remaining < 0.0:
		tracker_count = 0
		_tracker_target = 0
	for target in _revealed.keys():
		_revealed[target] = maxf(0.0, float(_revealed[target]) - delta)
		if float(_revealed[target]) <= 0.0:
			_revealed.erase(target)
			_reveal_targets.erase(target)
	# Registered activations last longer than every existing offensive flight.
	for activation in _modules.keys():
		_modules[activation].remaining -= delta
		if float(_modules[activation].remaining) <= 0.0:
			_modules.erase(activation)


func emit_weapon() -> Dictionary:
	_serial += 1
	var attack := {"id": _serial, "epoch": _epoch, "multiplier": 1.0, "slow": false, "targets": {}, "reactor_seen": false}
	if real_dead:
		return attack
	if passive_id == "alternator" and alternator_remaining > 0.0:
		attack.multiplier = 1.0 + float(tuning.damage_bonus)
		alternator_remaining = 0.0
		pulse_remaining = 0.25
	if passive_id == "inertia" and inertia_remaining > 0.0:
		attack.slow = true
		attack["slow_percent"] = float(tuning.slow_percent)
		attack["slow_duration"] = float(tuning.slow_duration)
		inertia_remaining = 0.0
		pulse_remaining = 0.25
	return attack


func register_module(activation: String) -> void:
	if activation != "" and not real_dead and not _modules.has(activation):
		_modules[activation] = {"remaining": 60.0, "used": false}


func module_hit(activation: String, effective: float) -> void:
	if real_dead or passive_id != "alternator" or effective <= 0.0 or not _modules.has(activation) or bool(_modules[activation].used):
		return
	_modules[activation].used = true
	alternator_remaining = float(tuning.duration)
	pulse_remaining = 0.25


func dash_finished(admissible: bool) -> void:
	mobility_finished(admissible)


func mobility_finished(admissible: bool = true) -> void:
	if admissible and not real_dead and passive_id == "inertia":
		inertia_remaining = float(tuning.window)
		pulse_remaining = 0.25


## Called only AFTER direct hostile damage has been accepted by the target.
## Component IDs stay in CombatState; this shared context identifies the attack.
func weapon_hit(target: Node, effective: float, attack: Dictionary, offensive_cooldown: float) -> float:
	if effective <= 0.0 or not combat_target(target) or attack.is_empty():
		return 0.0
	var target_id := target.get_instance_id()
	if attack.targets.has(target_id):
		return 0.0
	attack.targets[target_id] = true
	# An emitted attack keeps its own effect even after the owner's readiness
	# expired, or their equipment/life changed. No new proc is generated by it.
	if bool(attack.get("slow", false)) and target.has_method("apply_slow"):
		target.call("apply_slow", float(attack.slow_duration), float(attack.slow_percent), "passive:inertia")
	if real_dead or int(attack.get("epoch", -1)) != _epoch:
		return 0.0
	var reduction := 0.0
	if passive_id == "auxiliary_reactor" and not bool(attack.reactor_seen):
		attack.reactor_seen = true
		if reactor_remaining <= 0.0 and offensive_cooldown > 0.0:
			reduction = minf(offensive_cooldown, float(tuning.reduction))
			reactor_remaining = float(tuning.interval)
			pulse_remaining = 0.25
	if passive_id != "tracker" or _revealed.has(target_id):
		return reduction
	# Each target is counted once by this immutable attack's target ledger.
	# A cleave touching another opponent still switches the tracked target.
	if _tracker_target != target_id or tracker_remaining < 0.0:
		_tracker_target = target_id
		tracker_count = 0
	tracker_count += 1
	tracker_remaining = float(tuning.gap)
	if tracker_count >= int(tuning.hits):
		tracker_count = 0
		tracker_remaining = 0.0
		_revealed[target_id] = float(tuning.duration)
		_reveal_targets[target_id] = weakref(target)
		if target.has_method("apply_spotted"):
			target.call("apply_spotted", float(tuning.duration), "passive:tracker")
		pulse_remaining = 0.25
	return reduction


func snapshot() -> Dictionary:
	return {"reactor": reactor_remaining, "marks": tracker_count, "gap": maxf(0.0, tracker_remaining),
		"alternator": alternator_remaining, "inertia": inertia_remaining, "pulse": pulse_remaining, "reveal": reveal_remaining(), "hits": int(tuning.get("hits", 3))}


static func combat_target(target: Node) -> bool:
	return is_instance_valid(target) and target.has_method("get_max_health") and not target.is_in_group("prototype0_homing_rockets")


static func shield_health(target: Node) -> float:
	if not combat_target(target):
		return 0.0
	var state = target.get("combat_state")
	return float(state.shield_health) if state != null else 0.0


static func accepted_damage(target: Node, health_damage: float, shield_before: float) -> float:
	return health_damage + maxf(0.0, shield_before - shield_health(target))


func reveal_remaining() -> float:
	var longest := replica_reveal_remaining
	for remaining in _revealed.values():
		longest = maxf(longest, float(remaining))
	return longest


func revealed_targets() -> Array[Node3D]:
	var result: Array[Node3D] = []
	for ref: WeakRef in _reveal_targets.values():
		var target := ref.get_ref() as Node3D
		if is_instance_valid(target):
			result.append(target)
	return result


func restore_snapshot(value: Dictionary) -> void:
	reactor_remaining = float(value.get("reactor", 0.0))
	tracker_count = int(value.get("marks", 0))
	tracker_remaining = float(value.get("gap", 0.0))
	alternator_remaining = float(value.get("alternator", 0.0))
	inertia_remaining = float(value.get("inertia", 0.0))
	pulse_remaining = float(value.get("pulse", 0.0))
	replica_reveal_remaining = float(value.get("reveal", 0.0))

var passive_id := "baroud"
var baroud_max_health := BAROUD_MAX_HEALTH
var baroud_duration := BAROUD_DURATION
var omnivamp_rate := OMNIVAMP_RATE
var baroud_used := false
var baroud_active := false
var baroud_health := 0.0
var baroud_remaining := 0.0
var real_dead := false


func configure(next_passive_id: String) -> void:
	var selected := next_passive_id if next_passive_id in IDS else ""
	if selected != passive_id:
		clear_triggers()
	passive_id = selected
	tuning = DATA.MODULE_DEFINITIONS.get(passive_id, {}).duplicate(true)


func reset() -> void:
	clear_triggers()
	baroud_used = false
	baroud_active = false
	baroud_health = 0.0
	baroud_remaining = 0.0
	real_dead = false


func intercept_damage(amount: float, current_health: float, blocked: bool = false) -> Dictionary:
	var result := {"effective": 0.0, "triggered_baroud": false, "real_death": false}
	if blocked or amount <= 0.0 or real_dead:
		return result
	if baroud_active:
		var effective := minf(amount, baroud_health)
		baroud_health = maxf(0.0, baroud_health - effective)
		result["effective"] = effective
		if baroud_health <= 0.0:
			_end_baroud_as_death(result)
		return result
	if passive_id == "baroud" and not baroud_used and current_health > 0.0 and amount >= current_health:
		baroud_used = true
		baroud_active = true
		baroud_health = baroud_max_health
		baroud_remaining = baroud_duration
		result["triggered_baroud"] = true
		return result
	var effective_normal := minf(amount, maxf(0.0, current_health))
	result["effective"] = effective_normal
	if current_health - effective_normal <= 0.0:
		real_dead = true
		result["real_death"] = true
	return result


func process(delta: float) -> bool:
	tick_triggers(maxf(0.0, delta))
	if delta <= 0.0 or not baroud_active or real_dead:
		return false
	baroud_remaining = maxf(0.0, baroud_remaining - delta)
	baroud_health = maxf(0.0, baroud_health - BAROUD_DRAIN_PER_SECOND * delta)
	if baroud_remaining <= 0.0 or baroud_health <= 0.0:
		baroud_active = false
		baroud_health = 0.0
		real_dead = true
		return true
	return false


func can_heal() -> bool:
	return not baroud_active and not real_dead


func omnivamp_heal_for(effective_damage: float) -> float:
	if passive_id != "omnivamp" or effective_damage <= 0.0 or real_dead:
		return 0.0
	return effective_damage * omnivamp_rate


func _end_baroud_as_death(result: Dictionary) -> void:
	clear_triggers()
	baroud_active = false
	baroud_health = 0.0
	baroud_remaining = 0.0
	real_dead = true
	result["real_death"] = true


static func resolve_simultaneous_death(left_dead: bool, right_dead: bool) -> String:
	if left_dead and right_dead:
		return "draw"
	if left_dead:
		return "right"
	if right_dead:
		return "left"
	return "none"
