"""Audition specification: original Stable Audio sources for five modules."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SR = 44100
RUNTIME = Path(r"C:\Users\BOTTEROOOW\Tools\stable-audio-3\optimized\tflite")
PYTHON = RUNTIME / ".venv/Scripts/python.exe"
CLI = RUNTIME / "scripts/sa3_tflite.py"
INSPECTION_PYTHON = Path(r"C:\Users\BOTTEROOOW\.codex\runtimes\stable-audio-3\.venv\Scripts\python.exe")
INSPECTOR = Path(r"C:\Users\BOTTEROOOW\.codex\skills\generate-local-sfx\scripts\inspect_sfx.py")
NEGATIVE = "music, melody, speech, voices, narration, drill, jackhammer, automatic gunfire, regular repeated impacts, alarm siren, long reverb, room ambience, clipping, low fidelity"
MODULES = {
    "rocket_basket": {"name": "Panier roquettes", "direction": "Mécanique pneumatique, poussée de gaz et explosions compactes.", "scenario": [("rocket-arm", .50, 1), ("rocket-volley", .80, 1), ("rocket-propulsion", 1.02, .60), ("rocket-impact", 2.08, 1), ("rocket-destroyed", 3.15, 1)]},
    "counter": {"name": "Counter", "direction": "Garde tendue, interception sèche et énergie capturée puis libérée.", "scenario": [("counter-guard", .50, 1), ("counter-intercept", .96, 1), ("counter-overload", 1.05, .85), ("counter-discharge", 2.40, 1)]},
    "projector": {"name": "Projector", "direction": "Pression brève, onde grave et souffle physique ; déclenchement automatique distinct.", "scenario": [("projector-charge", .50, 1), ("projector-wave", .68, 1), ("projector-repulse", .73, .75), ("projector-passive", 2.40, 1)]},
    "permutation": {"name": "Permutation", "direction": "Ombre électrique furtive, échange rapide et verrouillage du bouclier.", "scenario": [("permutation-send", .50, 1), ("permutation-travel", .68, .65), ("permutation-swap", .96, 1), ("permutation-shield", 1.02, .80)]},
    "eclipse": {"name": "Éclipse", "direction": "Aspiration sombre, particules et arrivée explosive avec braises.", "scenario": [("eclipse-aim", .50, 1), ("eclipse-vanish", 1.35, 1), ("eclipse-travel", 1.35, .70), ("eclipse-arrival", 1.60, 1), ("eclipse-shield", 1.66, .85)]},
}

# id, module, French label, final seconds, level RMS dBFS, shape, prompt.
ROWS = [
    ("rocket-arm", "rocket_basket", "Ouverture / armement", .30, -23, "accent", "One compact robotic rocket rack opening and arming, a short pneumatic metal latch slide ending in one firm steel locking click, close dry isolated studio game sound effect, one short mechanical action then silence"),
    ("rocket-volley", "rocket_basket", "Lancement de la salve", .48, -20, "accent", "One compact volley of five miniature rockets leaving a robot launcher almost together, one punchy clustered ignition puff with compressed air thrust and a short metal rack kick, close dry isolated game sound effect, brief cohesive launch then silence, not machine gun fire"),
    ("rocket-propulsion", "rocket_basket", "Propulsion en vol · boucle", 1.20, -30, "loop", "Close small rocket exhaust already in flight, steady restrained rushing hot gas with soft turbulent fiery grit, smooth continuous propulsion texture, dry isolated game sound effect, no ignition blast, no impacts, no repeating pulses, no music"),
    ("rocket-impact", "rocket_basket", "Explosion à l’impact", .65, -19, "accent", "One small guided rocket hitting steel robot armor, sharp compact explosive crack, short low pressure punch and gritty metal fragments falling away, close dry isolated game sound effect, single fast explosion then silence, no cinematic long boom"),
    ("rocket-destroyed", "rocket_basket", "Destruction en vol", .38, -23, "accent", "One miniature rocket destroyed in midair, brittle metal shell snapping with a compact fiery pop and light debris fizz, close dry isolated game sound effect, one small brief disintegration then silence, lighter than a direct impact explosion"),
    ("counter-guard", "counter", "Activation de la garde", .12, -25, "accent", "One robot defensive guard snapping into place, tense steel shield latch and a very short restrained electrical thrum, close dry isolated game sound effect, instant tight mechanical activation then silence, no long charge"),
    ("counter-intercept", "counter", "Interception", .22, -21, "accent", "One incoming energy shot intercepted by a robot guard, crisp bright steel deflection crack followed by a compact electrical absorption snap, close dry isolated game sound effect, single sharp parry then silence, no explosion"),
    ("counter-overload", "counter", "Surcharge obtenue", .25, -27, "accent", "One robot capacitor capturing energy after a successful parry, a short rising restrained electrical resonance ending in a firm dry energized latch, close isolated game sound effect, clear brief energy ready cue then silence, no melody, no alarm"),
    ("counter-discharge", "counter", "Décharge de surcharge à l’impact", .48, -20, "accent", "One stored defensive energy charge releasing into steel armor at contact, punchy compact electrical burst with a solid metal crack and a short low pressure kick, close dry isolated game sound effect, single discharge then silence, no long laser beam"),
    ("projector-charge", "projector", "Montée en puissance", .18, -25, "accent", "One compact robot pressure projector building up quickly, tight compressed air intake with a low tense physical resonance rising briefly, close dry isolated game sound effect, single short charging gesture then silence, no sustained hum"),
    ("projector-wave", "projector", "Départ de l’onde", .46, -22, "accent", "One circular repulsion shockwave released by a robot projector, deep rounded pressure thump followed by a short expanding air wash, close dry isolated game sound effect, one compact non explosive force pulse then silence"),
    ("projector-repulse", "projector", "Souffle de répulsion", .42, -26, "accent", "One short forceful air shove pushing heavy metal away, broad dry low rushing pressure sweep with a restrained gritty air edge, close isolated game sound effect, one quick push then silence, no impact explosion"),
    ("projector-passive", "projector", "Déclenchement automatique · faibles PV", .62, -22, "accent", "One emergency robot repulsion field activating instantly, two close compact pressure pulses within one brief burst with a crisp mechanical safety latch and a short outward air wash, dry isolated game sound effect, distinctive urgent force release then silence, no alarm siren, no melody"),
    ("permutation-send", "permutation", "Envoi de l’ombre électrique", .18, -25, "accent", "One dark electrical shadow dart launched from a robot, compact dry electrostatic snap and fast wispy air release, close isolated game sound effect, one quick furtive gesture then silence, no firearm shot"),
    ("permutation-travel", "permutation", "Déplacement de l’ombre", .32, -29, "accent", "One electrical shadow gliding swiftly through the air, soft flowing granular static and a thin dark air whisper, close dry isolated game sound effect, single very short smooth passing sweep then silence, no tonal laser, no repeating pulses"),
    ("permutation-swap", "permutation", "Échange des positions", .38, -22, "accent", "One instantaneous exchange of two robot positions, paired inward air suction and outward electrical snap joined in one compact spatial flip, close dry isolated game sound effect, one fast teleport swap then silence, no long whoosh"),
    ("permutation-shield", "permutation", "Apparition du bouclier", .28, -27, "accent", "One protective energy shell locking around a robot, short clear glassy metal resonance with a firm electrical seal click, close dry isolated game sound effect, one discreet shield activation then silence, no melody, no alarm"),
    ("eclipse-aim", "eclipse", "Préparation pendant la sélection", .48, -27, "accent", "One robot preparing a shadow teleport destination, restrained dark air gathering with fine ember-like crackles and a short low tension swell, close dry isolated game sound effect, one brief preparation gesture then silence, no ominous music drone"),
    ("eclipse-vanish", "eclipse", "Disparition", .12, -24, "accent", "One robot vanishing into dark particles, extremely quick inward vacuum pop with a dry dusty ember hiss, close isolated game sound effect, single abrupt disappearance then silence, no explosion"),
    ("eclipse-travel", "eclipse", "Trajet en particules", .25, -29, "accent", "One stream of dark glowing particles rushing past, light textured air streak with tiny dry ember sparks, close isolated game sound effect, one very short flowing transit gesture then silence, no motor, no music"),
    ("eclipse-arrival", "eclipse", "Explosion à l’arrivée", .78, -19, "accent", "One robot rematerializing in a compact fiery shadow explosion, strong rounded low pressure punch with a gritty ember crack and short dusty flame release, close dry isolated game sound effect, single immediate explosive arrival then silence, no long cinematic rumble"),
    ("eclipse-shield", "eclipse", "Bouclier obtenu après une touche", .30, -27, "accent", "One robot gaining a protective shield from a successful fiery teleport hit, short warm steel and glass energy locking resonance with a tiny ember crackle, close dry isolated game sound effect, one discreet success cue then silence, no music or melody"),
]
CUES = [dict(id=row[0], module=row[1], label=row[2], duration=row[3], rms_db=row[4], kind=row[5], prompt=row[6], seed=26100200+i) for i,row in enumerate(ROWS,1)]
